# Application Name and Port
spring.application.name=employee-management-tool
server.port=8071
# Freemarker Configuration
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.freemarker.cache=false
# Hibernate and SQL Configuration
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Spring MVC Configuration
spring.mvc.pathmatch.matching-strategy=path-pattern-parser
# General SQL Initialization (can be overridden in environment-specific files)
spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.show_sql=true
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
# JWT configuration
jwt.expiration=3600000
jwt.expected-issuer=myAuthService
jwt.expected-audience=employeeManagementTool
spring.data.rest.enabled=false
#spring.data.rest.base-path=  # Leave empty to disable
spring.data.rest.default-media-type=application/hal+json
spring.data.rest.detection-strategy=ANNOTATED
# no benifit of this property need to chekc and remove TODO
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.security=TRACE
security-config.allowed-paths=/h2/**,/swagger-ui/**,/v3/api-docs/**
security-config.cors.allowed-origins=http://localhost:4200
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/employee-management
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/employee-management/protocol/openid-connect/certs
# below is very important to find issues logging level
#logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
#logging.level.root=DEBUG
#logging.level.org.springframework=TRACE
#logging.level.org.springframework.web=TRACE
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db?options=-c%20search_path=user_schema,employee_schema
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.platform=postgresql
# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/user_db
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=user_schema,employee_schema
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
# Flyway Debugging (Optional, but useful for troubleshooting)
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.flywaydb=TRACE
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.flyway.out-of-order=true



