apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pgadmin-pvc
  annotations:
    "helm.sh/resource-policy": keep  # Prevent Helm from deleting PVC on uninstall
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
