apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
  labels:
    app: {{ .Release.Name }}-pgadmin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.pgadmin.nodePort }}
  selector:
    app: {{ .Release.Name }}-pgadmin
